export const PERM_VIEW_TEAM_SETTINGS = 'PERM_VIEW_TEAM_SETTINGS';
export const PERM_UPDATE_TEAM_DETAILS = 'PERM_UPDATE_TEAM_DETAILS';
export const PERM_INVITE_TEAM_MEMBERS = 'PERM_INVITE_TEAM_MEMBERS';
export const PERM_UPDATE_TEAM_MEMBERS = 'PERM_UPDATE_TEAM_MEMBERS';
export const PERM_REMOVE_TEAM_MEMBERS = 'PERM_REMOVE_TEAM_MEMBERS';
export const PERM_UPDATE_TEAM_ROLES = 'PERM_UPDATE_TEAM_ROLES';
export const PERM_UPDATE_TEAM_PERMS = 'PERM_UPDATE_TEAM_PERMS';
export const PERM_CREATE_TEAM_PROJECT = 'PERM_CREATE_TEAM_PROJECT';
export const PERM_EDIT_TEAM_PROJECT = 'PERM_EDIT_TEAM_PROJECT';
export const PERM_REMOVE_TEAM_PROJECT = 'PERM_REMOVE_TEAM_PROJECT';
export const PERM_ADD_TASK = 'PERM_ADD_TASK';
export const PERM_EDIT_OTHER_TASK = 'PERM_EDIT_OTHER_TASK';
export const PERM_DELETE_OTHER_TASK = 'PERM_DELETE_OTHER_TASK';

export const permissionLabels = {
    [PERM_VIEW_TEAM_SETTINGS]: 'View Team Settings',
    [PERM_UPDATE_TEAM_DETAILS]: 'Update Team Details',
    [PERM_INVITE_TEAM_MEMBERS]: 'Invite Team Members',
    [PERM_UPDATE_TEAM_MEMBERS]: 'Update Team Members',
    [PERM_REMOVE_TEAM_MEMBERS]: 'Remove Team Members',
    [PERM_UPDATE_TEAM_ROLES]: 'Update Team Roles',
    [PERM_UPDATE_TEAM_PERMS]: 'Update Team Permissions',
    [PERM_CREATE_TEAM_PROJECT]: 'Create Team Project',
    [PERM_EDIT_TEAM_PROJECT]: 'Edit Team Project',
    [PERM_REMOVE_TEAM_PROJECT]: 'Remove Team Project',
    [PERM_ADD_TASK]: 'Add Task',
    [PERM_EDIT_OTHER_TASK]: 'Edit Other Members Tasks',
    [PERM_DELETE_OTHER_TASK]: 'Delete Other Members Tasks',
};

// So it can be imported as a single object
export default {
    PERM_VIEW_TEAM_SETTINGS,
    PERM_UPDATE_TEAM_DETAILS,
    PERM_INVITE_TEAM_MEMBERS,
    PERM_UPDATE_TEAM_MEMBERS,
    PERM_REMOVE_TEAM_MEMBERS,
    PERM_UPDATE_TEAM_ROLES,
    PERM_UPDATE_TEAM_PERMS,
    PERM_CREATE_TEAM_PROJECT,
    PERM_EDIT_TEAM_PROJECT,
    PERM_REMOVE_TEAM_PROJECT,
    PERM_ADD_TASK,
    PERM_EDIT_OTHER_TASK,
    PERM_DELETE_OTHER_TASK,
};
